version: '3'

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: zbat_jenkins
    volumes:
      - /data/jenkins:/var
      - /data/jenkins/jenkins_home:/var/jenkins_home
    working_dir: /var/jenkins_home
    ports:
      - 8080:8080
      - 5000:5000
      - 50000:50000
    restart: unless-stopped
    tty: true
    stdin_open: true
    privileged: true
