version: '3'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: zbat_kibana
    environment:
      SERVER_NAME: zbat_kibana.cloud.zingbox.com
      ELASTICSEARCH_URL: http://192.168.20.67:9200
    ports:
      - "5601:5601"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: zbat_elasticsearch
    volumes:
      - elastic-vol
    ports:
      - "9200:9200"
